# --- !Ups

insert into comp_player (name, position) values ('Adam Jones', 'Prop');
insert into comp_player (name, position) values ('Alex Corbisiero', 'Prop');
insert into comp_player (name, position) values ('Andrew Sheridan', 'Prop');
insert into comp_player (name, position) values ('Cian Healy', 'Prop');
insert into comp_player (name, position) values ('Dan Cole', 'Prop');
insert into comp_player (name, position) values ('Dave Kilcoyne', 'Prop');
insert into comp_player (name, position) values ('David Wilson', 'Prop');
insert into comp_player (name, position) values ('Euan Murray', 'Prop');
insert into comp_player (name, position) values ('Geoff Cross', 'Prop');
insert into comp_player (name, position) values ('Gethin Jenkins', 'Prop');
insert into comp_player (name, position) values ('Joe Marler', 'Prop');
insert into comp_player (name, position) values ('Mako Vunipola', 'Prop');
insert into comp_player (name, position) values ('Michael Bent', 'Prop');
insert into comp_player (name, position) values ('Mike Ross', 'Prop');
insert into comp_player (name, position) values ('Paul James', 'Prop');
insert into comp_player (name, position) values ('Ryan Bevington', 'Prop');
insert into comp_player (name, position) values ('Ryan Grant', 'Prop');
insert into comp_player (name, position) values ('Scott Andrews', 'Prop');
insert into comp_player (name, position) values ('Tom Court', 'Prop');
insert into comp_player (name, position) values ('Dylan Hartley', 'Hooker');
insert into comp_player (name, position) values ('Ken Owens', 'Hooker');
insert into comp_player (name, position) values ('Matthew Rees', 'Hooker');
insert into comp_player (name, position) values ('Richard Hibbard', 'Hooker');
insert into comp_player (name, position) values ('Richardt Strauss', 'Hooker');
insert into comp_player (name, position) values ('Rob Webber', 'Hooker');
insert into comp_player (name, position) values ('Rory Best', 'Hooker');
insert into comp_player (name, position) values ('Ross Ford', 'Hooker');
insert into comp_player (name, position) values ('Sean Cronin', 'Hooker');
insert into comp_player (name, position) values ('Tom Youngs', 'Hooker');
insert into comp_player (name, position) values ('Alastair Kellock', 'Lock');
insert into comp_player (name, position) values ('Andrew Coombs', 'Lock');
insert into comp_player (name, position) values ('Bradley Davies', 'Lock');
insert into comp_player (name, position) values ('Courtney Lawes', 'Lock');
insert into comp_player (name, position) values ('Devin Toner', 'Lock');
insert into comp_player (name, position) values ('Donnacha Ryan', 'Lock');
insert into comp_player (name, position) values ("Donncha O'Callaghan", 'Lock');
insert into comp_player (name, position) values ('Geoff Parling', 'Lock');
insert into comp_player (name, position) values ('Ian Evans', 'Lock');
insert into comp_player (name, position) values ('Jim Hamilton', 'Lock');
insert into comp_player (name, position) values ('Joe Launchbury', 'Lock');
insert into comp_player (name, position) values ('Leo Cullen', 'Lock');
insert into comp_player (name, position) values ('Lou Reed', 'Lock');
insert into comp_player (name, position) values ('Mouritz Botha', 'Lock');
insert into comp_player (name, position) values ('Nathan Hines', 'Lock');
insert into comp_player (name, position) values ("Paul O'Connel", 'Lock');
insert into comp_player (name, position) values ('Richie Gray', 'Lock');
insert into comp_player (name, position) values ('Aaron Shingler', 'Back Row');
insert into comp_player (name, position) values ('Alasdair Strokosch', 'Back Row');
insert into comp_player (name, position) values ('Ben Morgan', 'Back Row');
insert into comp_player (name, position) values ('Billy Vunipola', 'Back Row');
insert into comp_player (name, position) values ('Calum Clark', 'Back Row');
insert into comp_player (name, position) values ('Chris Henry', 'Back Row');
insert into comp_player (name, position) values ('Chris Robshaw', 'Back Row');
insert into comp_player (name, position) values ('Dan Lydiate', 'Back Row');
insert into comp_player (name, position) values ('David Denton', 'Back Row');
insert into comp_player (name, position) values ('Gareth Delve', 'Back Row');
insert into comp_player (name, position) values ('James Haskell', 'Back Row');
insert into comp_player (name, position) values ('Jamie Heaslip', 'Back Row');
insert into comp_player (name, position) values ('Jonnie Beattie', 'Back Row');
insert into comp_player (name, position) values ('Justin Tipuric', 'Back Row');
insert into comp_player (name, position) values ('Kelly Brown', 'Back Row');
insert into comp_player (name, position) values ('Nick Easter', 'Back Row');
insert into comp_player (name, position) values ("Peter O'Mahony", 'Back Row');
insert into comp_player (name, position) values ('Richie Vernon', 'Back Row');
insert into comp_player (name, position) values ('Rob Harley', 'Back Row');
insert into comp_player (name, position) values ('Ryan Jones', 'Back Row');
insert into comp_player (name, position) values ('Roger Wilson', 'Back Row');
insert into comp_player (name, position) values ('Sam Warburton', 'Back Row');
insert into comp_player (name, position) values ("Sean O'Brien", 'Back Row');
insert into comp_player (name, position) values ('Shane Jennings', 'Back Row');
insert into comp_player (name, position) values ('Stephen Ferris', 'Back Row');
insert into comp_player (name, position) values ('Thomas Waldrom', 'Back Row');
insert into comp_player (name, position) values ('Toby Faletau', 'Back Row');
insert into comp_player (name, position) values ('Tom Croft', 'Back Row');
insert into comp_player (name, position) values ('Tom Johnson', 'Back Row');
insert into comp_player (name, position) values ('Tom Wood', 'Back Row');
insert into comp_player (name, position) values ('Ben Youngs', 'Scrum Half');
insert into comp_player (name, position) values ('Connor Murray', 'Scrum Half');
insert into comp_player (name, position) values ('Danny Care', 'Scrum Half');
insert into comp_player (name, position) values ('Eoin Reddan', 'Scrum Half');
insert into comp_player (name, position) values ('Greig Laidlaw', 'Scrum Half');
insert into comp_player (name, position) values ('Joe Simpson', 'Scrum Half');
insert into comp_player (name, position) values ('Lloyd Williams', 'Scrum Half');
insert into comp_player (name, position) values ('Mike Phillips', 'Scrum Half');
insert into comp_player (name, position) values ('Paul Marshall', 'Scrum Half');
insert into comp_player (name, position) values ('Peter Stringer', 'Scrum Half');
insert into comp_player (name, position) values ('Charlie Hodgson', 'Fly Half');
insert into comp_player (name, position) values ('Dan Biggar', 'Fly Half');
insert into comp_player (name, position) values ('Danny Cipriani', 'Fly Half');
insert into comp_player (name, position) values ('Duncan Weir', 'Fly Half');
insert into comp_player (name, position) values ('Freddie Burns', 'Fly Half');
insert into comp_player (name, position) values ('Gavin Henson', 'Fly Half');
insert into comp_player (name, position) values ('Ian Madigan', 'Fly Half');
insert into comp_player (name, position) values ('James Hook', 'Fly Half');
insert into comp_player (name, position) values ('Jonny Sexton', 'Fly Half');
insert into comp_player (name, position) values ('Jonny Wilkinson', 'Fly Half');
insert into comp_player (name, position) values ('Owen Farrell', 'Fly Half');
insert into comp_player (name, position) values ('Paddy Jackson', 'Fly Half');
insert into comp_player (name, position) values ('Rhys Priestland', 'Fly Half');
insert into comp_player (name, position) values ('Ruaridh Jackson', 'Fly Half');
insert into comp_player (name, position) values ('Toby Flood', 'Fly Half');
insert into comp_player (name, position) values ('Tom Heathcote', 'Fly Half');
insert into comp_player (name, position) values ('Anthony Allen', 'Centre');
insert into comp_player (name, position) values ('Billy Twelvetrees', 'Centre');
insert into comp_player (name, position) values ('Brad Barritt', 'Centre');
insert into comp_player (name, position) values ('Darren Cave', 'Centre');
insert into comp_player (name, position) values ("Eoin O'Malley", 'Centre');
insert into comp_player (name, position) values ('Fergus McFadden', 'Centre');
insert into comp_player (name, position) values ('Jamie Roberts', 'Centre');
insert into comp_player (name, position) values ('Joel Tomkins', 'Centre');
insert into comp_player (name, position) values ('Jonathan Davies', 'Centre');
insert into comp_player (name, position) values ('Jonathan Joseph', 'Centre');
insert into comp_player (name, position) values ('Jordan Turner-Hall', 'Centre');
insert into comp_player (name, position) values ('Keith Earls', 'Centre');
insert into comp_player (name, position) values ('Kyle Eastmond', 'Centre');
insert into comp_player (name, position) values ('Luke Marshall', 'Centre');
insert into comp_player (name, position) values ('Manu Tuilagi', 'Centre');
insert into comp_player (name, position) values ('Matt Scott', 'Centre');
insert into comp_player (name, position) values ('Max Evans', 'Centre');
insert into comp_player (name, position) values ('Scott Williams', 'Centre');
insert into comp_player (name, position) values ('Sean Lamont', 'Centre');
insert into comp_player (name, position) values ('Alex Cuthbert', 'Wing');
insert into comp_player (name, position) values ('Andrew Trimble', 'Wing');
insert into comp_player (name, position) values ('Chris Ashton', 'Wing');
insert into comp_player (name, position) values ('Christian Wade', 'Wing');
insert into comp_player (name, position) values ('Craig Gilroy', 'Wing');
insert into comp_player (name, position) values ('David Strettle', 'Wing');
insert into comp_player (name, position) values ('Eli Walker', 'Wing');
insert into comp_player (name, position) values ('George North', 'Wing');
insert into comp_player (name, position) values ('Johnny May', 'Wing');
insert into comp_player (name, position) values ('Luke Fitzgerald', 'Wing');
insert into comp_player (name, position) values ('Sean Maitland', 'Wing');
insert into comp_player (name, position) values ('Simon Zebo', 'Wing');
insert into comp_player (name, position) values ('Tim Visser', 'Wing');
insert into comp_player (name, position) values ('Tommy Bowe', 'Wing');
insert into comp_player (name, position) values ('Ugo Monye', 'Wing');
insert into comp_player (name, position) values ('Alex Goode', 'Full Back');
insert into comp_player (name, position) values ('Ben Foden', 'Full Back');
insert into comp_player (name, position) values ('Delon Armitage', 'Full Back');
insert into comp_player (name, position) values ('Lee Byrne', 'Full Back');
insert into comp_player (name, position) values ('Leigh Halfpenny', 'Full Back');
insert into comp_player (name, position) values ('Liam Williams', 'Full Back');
insert into comp_player (name, position) values ('Mike Brown', 'Full Back');
insert into comp_player (name, position) values ('Rob Kearney', 'Full Back');
insert into comp_player (name, position) values ('Stuart Hogg', 'Full Back');

# --- !Downs
 
DROP TABLE if exists comp_player;
